"""create price_history table

Revision ID: 01882c3969cb
Revises:
Create Date: 2026-09-05 14:38:28.885867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # required: autogenerate emits sqlmodel.sql.sqltypes.* but doesn't import it itself

# revision identifiers, used by Alembic.
revision: str = "01882c3969cb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_history",
        sa.Column(
            "ticker", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("adj_close", sa.Float(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price_history")
    # ### end Alembic commands ###
